### ISSUE TITLE
Deploy web to Now

### ISSUE THREAD

**Issue by duongdev** [targeek/storelammoc-marketplace#3]
# Task

- [ ] Auto deploy pull requests.
- [ ] Auto deploy staging.
- [ ] Auto deploy production.

https://zeit.co/guides/deploying-nextjs-with-now/
